services:
  db:
    image: mysql
    restart: always
    ports:
    - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:bdd_toon
    volumes:
      - db_toon:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql   
    networks:
      - mysql-phpmyadmin-java
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin-java

  toon:
    container_name: toon_container
    restart: always
    image: mazodev/toon:1.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:8080"
    environment:
      - IP_HOST=${IP_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
    networks:
      - mysql-phpmyadmin-java


volumes:
  db_toon:

networks:
  mysql-phpmyadmin-java:
